namespace Feliz.MaterialUI

//////////////////////////////////
/// THIS FILE IS AUTO-GENERATED //
//////////////////////////////////

open Fable.Core
open Fable.Core.JsInterop
open Fable.React
open Feliz

[<AutoOpen>]
module MuiHelpers =

  [<System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)>]
  let reactElement (el: ReactElementType) (props: 'a) : ReactElement =
    import "createElement" "react"
  
  [<System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)>]
  let createElement (el: ReactElementType) (properties: IReactProperty list) : ReactElement =
    reactElement el (createObj !!properties)

[<Erase>]
type Mui =

  static member inline appBar = createElement (importDefault "@material-ui/core/AppBar")
  static member inline avatar = createElement (importDefault "@material-ui/core/Avatar")
  static member inline backdrop = createElement (importDefault "@material-ui/core/Backdrop")
  static member inline badge = createElement (importDefault "@material-ui/core/Badge")
  static member inline bottomNavigationAction = createElement (importDefault "@material-ui/core/BottomNavigationAction")
  static member inline bottomNavigation = createElement (importDefault "@material-ui/core/BottomNavigation")
  static member inline breadcrumbs = createElement (importDefault "@material-ui/core/Breadcrumbs")
  static member inline buttonBase = createElement (importDefault "@material-ui/core/ButtonBase")
  static member inline buttonGroup = createElement (importDefault "@material-ui/core/ButtonGroup")
  static member inline button = createElement (importDefault "@material-ui/core/Button")
  static member inline cardActionArea = createElement (importDefault "@material-ui/core/CardActionArea")
  static member inline cardActions = createElement (importDefault "@material-ui/core/CardActions")
  static member inline cardContent = createElement (importDefault "@material-ui/core/CardContent")
  static member inline cardHeader = createElement (importDefault "@material-ui/core/CardHeader")
  static member inline cardMedia = createElement (importDefault "@material-ui/core/CardMedia")
  static member inline card = createElement (importDefault "@material-ui/core/Card")
  static member inline checkbox = createElement (importDefault "@material-ui/core/Checkbox")
  static member inline chip = createElement (importDefault "@material-ui/core/Chip")
  static member inline circularProgress = createElement (importDefault "@material-ui/core/CircularProgress")
  static member inline clickAwayListener = createElement (importDefault "@material-ui/core/ClickAwayListener")
  static member inline collapse = createElement (importDefault "@material-ui/core/Collapse")
  static member inline container = createElement (importDefault "@material-ui/core/Container")
  static member inline cssBaseline = createElement (importDefault "@material-ui/core/CssBaseline")
  static member inline dialogActions = createElement (importDefault "@material-ui/core/DialogActions")
  static member inline dialogContentText = createElement (importDefault "@material-ui/core/DialogContentText")
  static member inline dialogContent = createElement (importDefault "@material-ui/core/DialogContent")
  static member inline dialogTitle = createElement (importDefault "@material-ui/core/DialogTitle")
  static member inline dialog = createElement (importDefault "@material-ui/core/Dialog")
  static member inline divider = createElement (importDefault "@material-ui/core/Divider")
  static member inline drawer = createElement (importDefault "@material-ui/core/Drawer")
  static member inline expansionPanelActions = createElement (importDefault "@material-ui/core/ExpansionPanelActions")
  static member inline expansionPanelDetails = createElement (importDefault "@material-ui/core/ExpansionPanelDetails")
  static member inline expansionPanelSummary = createElement (importDefault "@material-ui/core/ExpansionPanelSummary")
  static member inline expansionPanel = createElement (importDefault "@material-ui/core/ExpansionPanel")
  static member inline fab = createElement (importDefault "@material-ui/core/Fab")
  static member inline fade = createElement (importDefault "@material-ui/core/Fade")
  static member inline filledInput = createElement (importDefault "@material-ui/core/FilledInput")
  static member inline formControlLabel = createElement (importDefault "@material-ui/core/FormControlLabel")
  static member inline formControl = createElement (importDefault "@material-ui/core/FormControl")
  static member inline formGroup = createElement (importDefault "@material-ui/core/FormGroup")
  static member inline formHelperText = createElement (importDefault "@material-ui/core/FormHelperText")
  static member inline formLabel = createElement (importDefault "@material-ui/core/FormLabel")
  static member inline gridListTileBar = createElement (importDefault "@material-ui/core/GridListTileBar")
  static member inline gridListTile = createElement (importDefault "@material-ui/core/GridListTile")
  static member inline gridList = createElement (importDefault "@material-ui/core/GridList")
  static member inline grid = createElement (importDefault "@material-ui/core/Grid")
  static member inline grow = createElement (importDefault "@material-ui/core/Grow")
  static member inline hidden = createElement (importDefault "@material-ui/core/Hidden")
  static member inline iconButton = createElement (importDefault "@material-ui/core/IconButton")
  static member inline icon = createElement (importDefault "@material-ui/core/Icon")
  static member inline inputAdornment = createElement (importDefault "@material-ui/core/InputAdornment")
  static member inline inputBase = createElement (importDefault "@material-ui/core/InputBase")
  static member inline inputLabel = createElement (importDefault "@material-ui/core/InputLabel")
  static member inline input = createElement (importDefault "@material-ui/core/Input")
  static member inline linearProgress = createElement (importDefault "@material-ui/core/LinearProgress")
  static member inline link = createElement (importDefault "@material-ui/core/Link")
  static member inline listItemAvatar = createElement (importDefault "@material-ui/core/ListItemAvatar")
  static member inline listItemIcon = createElement (importDefault "@material-ui/core/ListItemIcon")
  static member inline listItemSecondaryAction = createElement (importDefault "@material-ui/core/ListItemSecondaryAction")
  static member inline listItemText = createElement (importDefault "@material-ui/core/ListItemText")
  static member inline listItem = createElement (importDefault "@material-ui/core/ListItem")
  static member inline listSubheader = createElement (importDefault "@material-ui/core/ListSubheader")
  static member inline list = createElement (importDefault "@material-ui/core/List")
  static member inline menuItem = createElement (importDefault "@material-ui/core/MenuItem")
  static member inline menuList = createElement (importDefault "@material-ui/core/MenuList")
  static member inline menu = createElement (importDefault "@material-ui/core/Menu")
  static member inline mobileStepper = createElement (importDefault "@material-ui/core/MobileStepper")
  static member inline modal = createElement (importDefault "@material-ui/core/Modal")
  static member inline nativeSelect = createElement (importDefault "@material-ui/core/NativeSelect")
  static member inline noSsr = createElement (importDefault "@material-ui/core/NoSsr")
  static member inline outlinedInput = createElement (importDefault "@material-ui/core/OutlinedInput")
  static member inline paper = createElement (importDefault "@material-ui/core/Paper")
  static member inline popover = createElement (importDefault "@material-ui/core/Popover")
  static member inline popper = createElement (importDefault "@material-ui/core/Popper")
  static member inline portal = createElement (importDefault "@material-ui/core/Portal")
  static member inline radioGroup = createElement (importDefault "@material-ui/core/RadioGroup")
  static member inline radio = createElement (importDefault "@material-ui/core/Radio")
  static member inline rating = createElement (importDefault "@material-ui/lab/Rating")
  static member inline rootRef = createElement (importDefault "@material-ui/core/RootRef")
  static member inline select = createElement (importDefault "@material-ui/core/Select")
  static member inline skeleton = createElement (importDefault "@material-ui/lab/Skeleton")
  static member inline slide = createElement (importDefault "@material-ui/core/Slide")
  static member inline slider = createElement (importDefault "@material-ui/core/Slider")
  static member inline snackbarContent = createElement (importDefault "@material-ui/core/SnackbarContent")
  static member inline snackbar = createElement (importDefault "@material-ui/core/Snackbar")
  static member inline speedDialAction = createElement (importDefault "@material-ui/lab/SpeedDialAction")
  static member inline speedDialIcon = createElement (importDefault "@material-ui/lab/SpeedDialIcon")
  static member inline speedDial = createElement (importDefault "@material-ui/lab/SpeedDial")
  static member inline stepButton = createElement (importDefault "@material-ui/core/StepButton")
  static member inline stepConnector = createElement (importDefault "@material-ui/core/StepConnector")
  static member inline stepContent = createElement (importDefault "@material-ui/core/StepContent")
  static member inline stepIcon = createElement (importDefault "@material-ui/core/StepIcon")
  static member inline stepLabel = createElement (importDefault "@material-ui/core/StepLabel")
  static member inline step = createElement (importDefault "@material-ui/core/Step")
  static member inline stepper = createElement (importDefault "@material-ui/core/Stepper")
  static member inline svgIcon = createElement (importDefault "@material-ui/core/SvgIcon")
  static member inline swipeableDrawer = createElement (importDefault "@material-ui/core/SwipeableDrawer")
  static member inline switch = createElement (importDefault "@material-ui/core/Switch")
  static member inline tab = createElement (importDefault "@material-ui/core/Tab")
  static member inline tableBody = createElement (importDefault "@material-ui/core/TableBody")
  static member inline tableCell = createElement (importDefault "@material-ui/core/TableCell")
  static member inline tableFooter = createElement (importDefault "@material-ui/core/TableFooter")
  static member inline tableHead = createElement (importDefault "@material-ui/core/TableHead")
  static member inline tablePagination = createElement (importDefault "@material-ui/core/TablePagination")
  static member inline tableRow = createElement (importDefault "@material-ui/core/TableRow")
  static member inline tableSortLabel = createElement (importDefault "@material-ui/core/TableSortLabel")
  static member inline table = createElement (importDefault "@material-ui/core/Table")
  static member inline tabs = createElement (importDefault "@material-ui/core/Tabs")
  static member inline textField = createElement (importDefault "@material-ui/core/TextField")
  static member inline textareaAutosize = createElement (importDefault "@material-ui/core/TextareaAutosize")
  static member inline toggleButtonGroup = createElement (importDefault "@material-ui/lab/ToggleButtonGroup")
  static member inline toggleButton = createElement (importDefault "@material-ui/lab/ToggleButton")
  static member inline toolbar = createElement (importDefault "@material-ui/core/Toolbar")
  static member inline tooltip = createElement (importDefault "@material-ui/core/Tooltip")
  static member inline touchRipple = createElement (importDefault "@material-ui/core/ButtonBase/TouchRipple.js/TouchRipple")
  static member inline treeItem = createElement (importDefault "@material-ui/lab/TreeItem")
  static member inline treeView = createElement (importDefault "@material-ui/lab/TreeView")
  static member inline typography = createElement (importDefault "@material-ui/core/Typography")
  static member inline zoom = createElement (importDefault "@material-ui/core/Zoom")
