namespace Feliz.MaterialUI
  
(*////////////////////////////////
/// THIS FILE IS AUTO-GENERATED //
////////////////////////////////*)

open Fable.Core
open Fable.Core.JsInterop
open Feliz
  
type IThemeProps = interface end


[<Erase>]
type themeProps =
  static member inline muiAppBar(props: IReactProperty list) : IThemeProps = unbox ("MuiAppBar", createObj !!props)
  static member inline muiAvatar(props: IReactProperty list) : IThemeProps = unbox ("MuiAvatar", createObj !!props)
  static member inline muiBackdrop(props: IReactProperty list) : IThemeProps = unbox ("MuiBackdrop", createObj !!props)
  static member inline muiBadge(props: IReactProperty list) : IThemeProps = unbox ("MuiBadge", createObj !!props)
  static member inline muiBottomNavigation(props: IReactProperty list) : IThemeProps = unbox ("MuiBottomNavigation", createObj !!props)
  static member inline muiBottomNavigationAction(props: IReactProperty list) : IThemeProps = unbox ("MuiBottomNavigationAction", createObj !!props)
  static member inline muiBreadcrumbs(props: IReactProperty list) : IThemeProps = unbox ("MuiBreadcrumbs", createObj !!props)
  static member inline muiButton(props: IReactProperty list) : IThemeProps = unbox ("MuiButton", createObj !!props)
  static member inline muiButtonBase(props: IReactProperty list) : IThemeProps = unbox ("MuiButtonBase", createObj !!props)
  static member inline muiButtonGroup(props: IReactProperty list) : IThemeProps = unbox ("MuiButtonGroup", createObj !!props)
  static member inline muiCard(props: IReactProperty list) : IThemeProps = unbox ("MuiCard", createObj !!props)
  static member inline muiCardActionArea(props: IReactProperty list) : IThemeProps = unbox ("MuiCardActionArea", createObj !!props)
  static member inline muiCardActions(props: IReactProperty list) : IThemeProps = unbox ("MuiCardActions", createObj !!props)
  static member inline muiCardContent(props: IReactProperty list) : IThemeProps = unbox ("MuiCardContent", createObj !!props)
  static member inline muiCardHeader(props: IReactProperty list) : IThemeProps = unbox ("MuiCardHeader", createObj !!props)
  static member inline muiCardMedia(props: IReactProperty list) : IThemeProps = unbox ("MuiCardMedia", createObj !!props)
  static member inline muiCheckbox(props: IReactProperty list) : IThemeProps = unbox ("MuiCheckbox", createObj !!props)
  static member inline muiChip(props: IReactProperty list) : IThemeProps = unbox ("MuiChip", createObj !!props)
  static member inline muiCircularProgress(props: IReactProperty list) : IThemeProps = unbox ("MuiCircularProgress", createObj !!props)
  static member inline muiClickAwayListener(props: IReactProperty list) : IThemeProps = unbox ("MuiClickAwayListener", createObj !!props)
  static member inline muiCollapse(props: IReactProperty list) : IThemeProps = unbox ("MuiCollapse", createObj !!props)
  static member inline muiContainer(props: IReactProperty list) : IThemeProps = unbox ("MuiContainer", createObj !!props)
  static member inline muiCssBaseline(props: IReactProperty list) : IThemeProps = unbox ("MuiCssBaseline", createObj !!props)
  static member inline muiDialog(props: IReactProperty list) : IThemeProps = unbox ("MuiDialog", createObj !!props)
  static member inline muiDialogActions(props: IReactProperty list) : IThemeProps = unbox ("MuiDialogActions", createObj !!props)
  static member inline muiDialogContent(props: IReactProperty list) : IThemeProps = unbox ("MuiDialogContent", createObj !!props)
  static member inline muiDialogContentText(props: IReactProperty list) : IThemeProps = unbox ("MuiDialogContentText", createObj !!props)
  static member inline muiDialogTitle(props: IReactProperty list) : IThemeProps = unbox ("MuiDialogTitle", createObj !!props)
  static member inline muiDivider(props: IReactProperty list) : IThemeProps = unbox ("MuiDivider", createObj !!props)
  static member inline muiDrawer(props: IReactProperty list) : IThemeProps = unbox ("MuiDrawer", createObj !!props)
  static member inline muiExpansionPanel(props: IReactProperty list) : IThemeProps = unbox ("MuiExpansionPanel", createObj !!props)
  static member inline muiExpansionPanelActions(props: IReactProperty list) : IThemeProps = unbox ("MuiExpansionPanelActions", createObj !!props)
  static member inline muiExpansionPanelDetails(props: IReactProperty list) : IThemeProps = unbox ("MuiExpansionPanelDetails", createObj !!props)
  static member inline muiExpansionPanelSummary(props: IReactProperty list) : IThemeProps = unbox ("MuiExpansionPanelSummary", createObj !!props)
  static member inline muiFab(props: IReactProperty list) : IThemeProps = unbox ("MuiFab", createObj !!props)
  static member inline muiFade(props: IReactProperty list) : IThemeProps = unbox ("MuiFade", createObj !!props)
  static member inline muiFilledInput(props: IReactProperty list) : IThemeProps = unbox ("MuiFilledInput", createObj !!props)
  static member inline muiFormControl(props: IReactProperty list) : IThemeProps = unbox ("MuiFormControl", createObj !!props)
  static member inline muiFormControlLabel(props: IReactProperty list) : IThemeProps = unbox ("MuiFormControlLabel", createObj !!props)
  static member inline muiFormGroup(props: IReactProperty list) : IThemeProps = unbox ("MuiFormGroup", createObj !!props)
  static member inline muiFormHelperText(props: IReactProperty list) : IThemeProps = unbox ("MuiFormHelperText", createObj !!props)
  static member inline muiFormLabel(props: IReactProperty list) : IThemeProps = unbox ("MuiFormLabel", createObj !!props)
  static member inline muiGrid(props: IReactProperty list) : IThemeProps = unbox ("MuiGrid", createObj !!props)
  static member inline muiGridList(props: IReactProperty list) : IThemeProps = unbox ("MuiGridList", createObj !!props)
  static member inline muiGridListTile(props: IReactProperty list) : IThemeProps = unbox ("MuiGridListTile", createObj !!props)
  static member inline muiGridListTileBar(props: IReactProperty list) : IThemeProps = unbox ("MuiGridListTileBar", createObj !!props)
  static member inline muiGrow(props: IReactProperty list) : IThemeProps = unbox ("MuiGrow", createObj !!props)
  static member inline muiHidden(props: IReactProperty list) : IThemeProps = unbox ("MuiHidden", createObj !!props)
  static member inline muiIcon(props: IReactProperty list) : IThemeProps = unbox ("MuiIcon", createObj !!props)
  static member inline muiIconButton(props: IReactProperty list) : IThemeProps = unbox ("MuiIconButton", createObj !!props)
  static member inline muiInput(props: IReactProperty list) : IThemeProps = unbox ("MuiInput", createObj !!props)
  static member inline muiInputAdornment(props: IReactProperty list) : IThemeProps = unbox ("MuiInputAdornment", createObj !!props)
  static member inline muiInputBase(props: IReactProperty list) : IThemeProps = unbox ("MuiInputBase", createObj !!props)
  static member inline muiInputLabel(props: IReactProperty list) : IThemeProps = unbox ("MuiInputLabel", createObj !!props)
  static member inline muiLinearProgress(props: IReactProperty list) : IThemeProps = unbox ("MuiLinearProgress", createObj !!props)
  static member inline muiLink(props: IReactProperty list) : IThemeProps = unbox ("MuiLink", createObj !!props)
  static member inline muiList(props: IReactProperty list) : IThemeProps = unbox ("MuiList", createObj !!props)
  static member inline muiListItem(props: IReactProperty list) : IThemeProps = unbox ("MuiListItem", createObj !!props)
  static member inline muiListItemAvatar(props: IReactProperty list) : IThemeProps = unbox ("MuiListItemAvatar", createObj !!props)
  static member inline muiListItemIcon(props: IReactProperty list) : IThemeProps = unbox ("MuiListItemIcon", createObj !!props)
  static member inline muiListItemSecondaryAction(props: IReactProperty list) : IThemeProps = unbox ("MuiListItemSecondaryAction", createObj !!props)
  static member inline muiListItemText(props: IReactProperty list) : IThemeProps = unbox ("MuiListItemText", createObj !!props)
  static member inline muiListSubheader(props: IReactProperty list) : IThemeProps = unbox ("MuiListSubheader", createObj !!props)
  static member inline muiMenu(props: IReactProperty list) : IThemeProps = unbox ("MuiMenu", createObj !!props)
  static member inline muiMenuItem(props: IReactProperty list) : IThemeProps = unbox ("MuiMenuItem", createObj !!props)
  static member inline muiMenuList(props: IReactProperty list) : IThemeProps = unbox ("MuiMenuList", createObj !!props)
  static member inline muiMobileStepper(props: IReactProperty list) : IThemeProps = unbox ("MuiMobileStepper", createObj !!props)
  static member inline muiModal(props: IReactProperty list) : IThemeProps = unbox ("MuiModal", createObj !!props)
  static member inline muiNativeSelect(props: IReactProperty list) : IThemeProps = unbox ("MuiNativeSelect", createObj !!props)
  static member inline muiNoSsr(props: IReactProperty list) : IThemeProps = unbox ("MuiNoSsr", createObj !!props)
  static member inline muiOutlinedInput(props: IReactProperty list) : IThemeProps = unbox ("MuiOutlinedInput", createObj !!props)
  static member inline muiPaper(props: IReactProperty list) : IThemeProps = unbox ("MuiPaper", createObj !!props)
  static member inline muiPopover(props: IReactProperty list) : IThemeProps = unbox ("MuiPopover", createObj !!props)
  static member inline muiPopper(props: IReactProperty list) : IThemeProps = unbox ("MuiPopper", createObj !!props)
  static member inline muiPortal(props: IReactProperty list) : IThemeProps = unbox ("MuiPortal", createObj !!props)
  static member inline muiRadio(props: IReactProperty list) : IThemeProps = unbox ("MuiRadio", createObj !!props)
  static member inline muiRadioGroup(props: IReactProperty list) : IThemeProps = unbox ("MuiRadioGroup", createObj !!props)
  static member inline muiRating(props: IReactProperty list) : IThemeProps = unbox ("MuiRating", createObj !!props)
  static member inline muiRootRef(props: IReactProperty list) : IThemeProps = unbox ("MuiRootRef", createObj !!props)
  static member inline muiSelect(props: IReactProperty list) : IThemeProps = unbox ("MuiSelect", createObj !!props)
  static member inline muiSkeleton(props: IReactProperty list) : IThemeProps = unbox ("MuiSkeleton", createObj !!props)
  static member inline muiSlide(props: IReactProperty list) : IThemeProps = unbox ("MuiSlide", createObj !!props)
  static member inline muiSlider(props: IReactProperty list) : IThemeProps = unbox ("MuiSlider", createObj !!props)
  static member inline muiSnackbar(props: IReactProperty list) : IThemeProps = unbox ("MuiSnackbar", createObj !!props)
  static member inline muiSnackbarContent(props: IReactProperty list) : IThemeProps = unbox ("MuiSnackbarContent", createObj !!props)
  static member inline muiSpeedDial(props: IReactProperty list) : IThemeProps = unbox ("MuiSpeedDial", createObj !!props)
  static member inline muiSpeedDialAction(props: IReactProperty list) : IThemeProps = unbox ("MuiSpeedDialAction", createObj !!props)
  static member inline muiSpeedDialIcon(props: IReactProperty list) : IThemeProps = unbox ("MuiSpeedDialIcon", createObj !!props)
  static member inline muiStep(props: IReactProperty list) : IThemeProps = unbox ("MuiStep", createObj !!props)
  static member inline muiStepButton(props: IReactProperty list) : IThemeProps = unbox ("MuiStepButton", createObj !!props)
  static member inline muiStepConnector(props: IReactProperty list) : IThemeProps = unbox ("MuiStepConnector", createObj !!props)
  static member inline muiStepContent(props: IReactProperty list) : IThemeProps = unbox ("MuiStepContent", createObj !!props)
  static member inline muiStepIcon(props: IReactProperty list) : IThemeProps = unbox ("MuiStepIcon", createObj !!props)
  static member inline muiStepLabel(props: IReactProperty list) : IThemeProps = unbox ("MuiStepLabel", createObj !!props)
  static member inline muiStepper(props: IReactProperty list) : IThemeProps = unbox ("MuiStepper", createObj !!props)
  static member inline muiSvgIcon(props: IReactProperty list) : IThemeProps = unbox ("MuiSvgIcon", createObj !!props)
  static member inline muiSwipeableDrawer(props: IReactProperty list) : IThemeProps = unbox ("MuiSwipeableDrawer", createObj !!props)
  static member inline muiSwitch(props: IReactProperty list) : IThemeProps = unbox ("MuiSwitch", createObj !!props)
  static member inline muiTab(props: IReactProperty list) : IThemeProps = unbox ("MuiTab", createObj !!props)
  static member inline muiTable(props: IReactProperty list) : IThemeProps = unbox ("MuiTable", createObj !!props)
  static member inline muiTableBody(props: IReactProperty list) : IThemeProps = unbox ("MuiTableBody", createObj !!props)
  static member inline muiTableCell(props: IReactProperty list) : IThemeProps = unbox ("MuiTableCell", createObj !!props)
  static member inline muiTableFooter(props: IReactProperty list) : IThemeProps = unbox ("MuiTableFooter", createObj !!props)
  static member inline muiTableHead(props: IReactProperty list) : IThemeProps = unbox ("MuiTableHead", createObj !!props)
  static member inline muiTablePagination(props: IReactProperty list) : IThemeProps = unbox ("MuiTablePagination", createObj !!props)
  static member inline muiTableRow(props: IReactProperty list) : IThemeProps = unbox ("MuiTableRow", createObj !!props)
  static member inline muiTableSortLabel(props: IReactProperty list) : IThemeProps = unbox ("MuiTableSortLabel", createObj !!props)
  static member inline muiTabs(props: IReactProperty list) : IThemeProps = unbox ("MuiTabs", createObj !!props)
  static member inline muiTextareaAutosize(props: IReactProperty list) : IThemeProps = unbox ("MuiTextareaAutosize", createObj !!props)
  static member inline muiTextField(props: IReactProperty list) : IThemeProps = unbox ("MuiTextField", createObj !!props)
  static member inline muiToggleButton(props: IReactProperty list) : IThemeProps = unbox ("MuiToggleButton", createObj !!props)
  static member inline muiToggleButtonGroup(props: IReactProperty list) : IThemeProps = unbox ("MuiToggleButtonGroup", createObj !!props)
  static member inline muiToolbar(props: IReactProperty list) : IThemeProps = unbox ("MuiToolbar", createObj !!props)
  static member inline muiTooltip(props: IReactProperty list) : IThemeProps = unbox ("MuiTooltip", createObj !!props)
  static member inline muiTouchRipple(props: IReactProperty list) : IThemeProps = unbox ("MuiTouchRipple", createObj !!props)
  static member inline muiTreeItem(props: IReactProperty list) : IThemeProps = unbox ("MuiTreeItem", createObj !!props)
  static member inline muiTreeView(props: IReactProperty list) : IThemeProps = unbox ("MuiTreeView", createObj !!props)
  static member inline muiTypography(props: IReactProperty list) : IThemeProps = unbox ("MuiTypography", createObj !!props)
  static member inline muiZoom(props: IReactProperty list) : IThemeProps = unbox ("MuiZoom", createObj !!props)
